import type { TikTokMarketConfig } from "../tiktok-config";
import { withSuiteBrand } from "@/lib/brand";

export const TH_MARKET: TikTokMarketConfig = {
  id: "th",
  name: "TH",
  fullName: "Thailand",
  flag: "🇹🇭",
  domain: "seller-th.tiktok.com",
  currency: { code: "THB", symbol: "฿", locale: "th-TH", decimals: 2 },
  categories: [
    { label: "Electronics", value: "electronics" },
    { label: "Non-electronics", value: "default" },
    { label: "Pre-order items", value: "preorder" },
  ],
  tax: {
    name: "VAT",
    defaultRate: 7,
    priceIncludesTaxByDefault: true,
    helpText: "Thailand public docs state platform service fees are VAT-inclusive by default, with separate corporate withholding rules.",
  },
  feeRules: [
    {
      id: "marketplace_commission_fee",
      type: "percentage",
      label: "Marketplace Commission Fee",
      description: "Public Thailand marketplace commission examples and category pages.",
      base: "item_after_seller_discount",
      defaultRate: 7.49,
      rateByCategory: {
        electronics: 7.49,
        default: 6.42,
        preorder: 6.42,
      },
    },
    {
      id: "commerce_growth_fee",
      type: "percentage",
      label: "Commerce Growth Fee",
      description: "Public Thailand commerce growth fee, tax-inclusive.",
      base: "item_after_seller_discount",
      defaultRate: 6.96,
      rateByCategory: {
        electronics: 5.89,
        default: 6.96,
        preorder: 6.96,
      },
      capAmount: 199,
    },
    {
      id: "preorder_service_fee",
      type: "percentage",
      label: "Pre-order Service Fee",
      description: "Additional public fee for pre-order items.",
      base: "item_after_seller_discount",
      defaultRate: 2.14,
      onlyCategories: ["preorder"],
    },
    {
      id: "transaction_fee",
      type: "percentage",
      label: "Transaction Fee",
      description: "Public Thailand transaction fee.",
      base: "buyer_payment_total",
      defaultRate: 3.21,
    },
    {
      id: "logistics_surcharge",
      type: "flat",
      label: "Seller Logistics Surcharge",
      description: "Optional surcharge for parcels above 3kg or route-specific rate card uplift.",
      sellerInput: true,
      inputLabel: "Logistics surcharge",
      defaultAmount: 0,
    },
  ],
  fulfillmentMethods: [
    {
      value: "self",
      label: "TikTok Shipping / Self-Managed",
      description: "Thailand public docs expose seller logistics surcharge, but not a warehouse storage card.",
      kind: "self",
    },
  ],
  defaults: {
    category: "default",
    fulfillmentMethod: "self",
    soldPrice: 590,
    sellerDiscount: 40,
    platformDiscount: 20,
    buyerShippingFee: 50,
    itemCost: 220,
    shippingCost: 35,
    affiliateRate: 8,
    adSpendPerUnit: 30,
    otherCosts: 0,
    taxRate: 7,
    priceIncludesTax: true,
    manualInputs: { logistics_surcharge: 0 },
  },
  seo: {
    title: withSuiteBrand("Thailand TikTok Shop Fee Calculator"),
    description: "Calculate Thailand TikTok Shop commission, commerce growth fee, transaction fee, VAT impact, and profit.",
    h1: "Thailand TikTok Shop Fee Calculator",
    subtitle: "Based on public Thailand TikTok Shop pages for marketplace commission, commerce growth fee, transaction fee, and VAT treatment.",
  },
  summary: {
    shortFeeSummary: "Thailand publicly documents marketplace commission, commerce growth fee, transaction fee, and pre-order fee rules.",
    taxSummary: "Platform services are modeled VAT-inclusive at 7% by default.",
    fulfillmentSummary: "No public storage card was found; logistics is modeled with seller shipping plus optional surcharge.",
    disclaimer: "Thailand public programs also include temporary small-seller discounts and waivers; add them manually only if they apply to your shop.",
  },
  docs: [
    {
      title: "Marketplace Commission Fee",
      url: "https://seller-th.tiktok.com/university/essay?knowledge_id=6837808312370945&lang=en",
      effectiveDate: "2026-04-01",
      scope: "Thailand marketplace commission formula",
    },
    {
      title: "Commerce Growth Fee",
      url: "https://seller-th.tiktok.com/university/essay?knowledge_id=4831419884979969&lang=en",
      effectiveDate: "2026-03-21",
      scope: "Thailand commerce growth fee and new-seller waiver note",
    },
    {
      title: "Transaction Fee",
      url: "https://seller-th.tiktok.com/university/essay?knowledge_id=10011830&lang=en",
      effectiveDate: "2026-03-21",
      scope: "Thailand transaction fee formula",
    },
    {
      title: "Basic Tax Information for Sellers",
      url: "https://seller-th.tiktok.com/university/essay?knowledge_id=8856797734799105&lang=en",
      effectiveDate: "2024-08-15",
      scope: "Thailand VAT and withholding treatment for platform fees",
    },
  ],
  notes: [
    "Thailand has strong public fee documentation, but detailed category tables still live in linked PDFs and images.",
    "The first-30-days commerce growth fee waiver is not forced into the result; use the manual fields if you qualify.",
  ],
};


