import type { TikTokMarketConfig } from "../tiktok-config";
import { withSuiteBrand } from "@/lib/brand";

const US_CATEGORIES = [
  { label: "Most Categories", value: "default" },
  { label: "Premium Jewelry", value: "jewelry_premium" },
  { label: "Other Jewelry", value: "jewelry_other" },
  { label: "Pre-Owned", value: "preowned" },
  { label: "Collectibles", value: "collectibles" },
];

export const US_MARKET: TikTokMarketConfig = {
  id: "us",
  name: "US",
  fullName: "United States",
  flag: "🇺🇸",
  domain: "shop.tiktok.com",
  currency: { code: "USD", symbol: "$", locale: "en-US", decimals: 2 },
  categories: US_CATEGORIES,
  tax: {
    name: "Sales tax",
    defaultRate: 0,
    priceIncludesTaxByDefault: false,
    helpText: "US listings are usually modeled pre-tax. The calculator keeps tax at 0% unless you override it.",
  },
  feeRules: [
    {
      id: "referral_fee",
      type: "percentage",
      label: "Referral Fee",
      description: "Public US referral fee schedule. If you qualify for a new-seller promo, override this rate manually.",
      base: "item_after_seller_discount",
      defaultRate: 6,
      rateByCategory: {
        jewelry_premium: 5,
        jewelry_other: 6,
        preowned: 5,
        collectibles: 6,
      },
      sellerInput: true,
      inputLabel: "Referral fee (%)",
    },
  ],
  fulfillmentMethods: [
    {
      value: "self",
      label: "Self-Fulfilled",
      description: "Seller handles shipping.",
      kind: "self",
    },
    {
      value: "platform",
      label: "FBT Fulfillment Fee",
      description: "Fulfilled by TikTok US public weight-tier card.",
      kind: "weight-tier",
      weightUnitLabel: "lb",
      dimensionUnitLabel: "in",
      chargeableWeightUnitLabel: "lb",
      maxWeight: 50,
      maxSide: 26,
      dimDivisor: 166,
      smallParcelRule: { maxWeight: 1, maxVolume: 166 },
      freeStorageDaysLabel: "First 60 days free",
      weightTiers: [
        { maxWeight: 0.5, label: "0–8 oz", singleUnit: 3.58, twoUnits: 2.86, threeUnits: 2.72, fourPlusUnits: 2.58 },
        { maxWeight: 1, label: "8 oz–1 lb", singleUnit: 3.78, twoUnits: 3.06, threeUnits: 2.92, fourPlusUnits: 2.78 },
        { maxWeight: 2, label: "1–2 lb", singleUnit: 4.15, twoUnits: 3.43, threeUnits: 3.29, fourPlusUnits: 3.15 },
        { maxWeight: 3, label: "2–3 lb", singleUnit: 4.58, twoUnits: 3.86, threeUnits: 3.72, fourPlusUnits: 3.58 },
        { maxWeight: 4, label: "3–4 lb", singleUnit: 5.15, twoUnits: 4.43, threeUnits: 4.29, fourPlusUnits: 4.15 },
        { maxWeight: 8, label: "4–8 lb", singleUnit: 5.75, twoUnits: 5.03, threeUnits: 4.89, fourPlusUnits: 4.75 },
        { maxWeight: 16, label: "8–16 lb", singleUnit: 7.15, twoUnits: 6.43, threeUnits: 6.29, fourPlusUnits: 6.15 },
        { maxWeight: 30, label: "16–30 lb", singleUnit: 9.75, twoUnits: 8.78, threeUnits: 8.64, fourPlusUnits: 8.5 },
        { maxWeight: 50, label: "30–50 lb", singleUnit: 15.25, twoUnits: 13.78, threeUnits: 13.64, fourPlusUnits: 13.5 },
      ],
      storageTiers: [
        { maxDays: 60, dailyRate: 0 },
        { maxDays: 90, dailyRate: 0.023 },
        { maxDays: 180, dailyRate: 0.05 },
        { maxDays: 270, dailyRate: 0.08 },
        { maxDays: Infinity, dailyRate: 0.12 },
      ],
    },
  ],
  defaults: {
    category: "default",
    fulfillmentMethod: "platform",
    soldPrice: 29.99,
    sellerDiscount: 0,
    platformDiscount: 0,
    buyerShippingFee: 0,
    itemCost: 8,
    shippingCost: 5,
    affiliateRate: 15,
    adSpendPerUnit: 3,
    otherCosts: 0,
    taxRate: 0,
    priceIncludesTax: false,
    weight: 1,
    dimensionLength: 10,
    dimensionWidth: 8,
    dimensionHeight: 4,
    unitsPerOrder: 1,
    storageDays: 30,
    manualInputs: { referral_fee: 6 },
  },
  seo: {
    title: withSuiteBrand("US TikTok Shop Fee Calculator"),
    description: "Calculate TikTok Shop US referral fees, FBT costs, creator commissions, and profit.",
    h1: "US TikTok Shop Fee Calculator",
    subtitle: "Model public US referral rates, FBT fulfillment and storage, creator commission, and net profit.",
  },
  summary: {
    shortFeeSummary: "Most public US categories use a 6% referral fee; select jewelry categories use 5%.",
    taxSummary: "US tax is modeled as optional sales tax, defaulting to 0%.",
    fulfillmentSummary: "Includes public US FBT fulfillment and storage fee tables plus self-fulfilled mode.",
    disclaimer: "US promo fields are optional seller overrides because promo eligibility is not guaranteed for every seller.",
  },
  docs: [
    {
      title: "TikTok Shop Merchant Terms of Service",
      url: "https://lf3-static.bytednsdoc.com/obj/eden-cn/lm-uvpahylwv-z/ljhwZthlaukjlkulzlp/user-agreement/TikTok%20Shop%20Merchant%20Terms%20of%20Service.pdf",
      effectiveDate: "2024-01-03",
      scope: "US seller fees and public platform terms",
    },
  ],
  notes: [
    "US public docs support a referral-fee-first model and optional FBT logistics cost modeling.",
    "New seller promotional pricing is exposed as an optional manual override instead of being forced into the result.",
  ],
};


