import type { TikTokMarketConfig } from "../tiktok-config";

export const VN_MARKET: TikTokMarketConfig = {
  id: "vn",
  name: "VN",
  fullName: "Vietnam",
  flag: "🇻🇳",
  domain: "seller-vn.tiktok.com",
  currency: { code: "VND", symbol: "₫", locale: "vi-VN", decimals: 0 },
  categories: [
    { label: "Marketplace Default", value: "default" },
    { label: "Mall Default", value: "mall" },
  ],
  sellerProfiles: [
    { label: "Marketplace seller", value: "marketplace" },
    { label: "Mall seller", value: "mall" },
    { label: "Verified tax code", value: "verified_tax" },
  ],
  tax: {
    name: "VAT + CIT on platform fees",
    defaultRate: 10,
    priceIncludesTaxByDefault: true,
    helpText: "Vietnam public docs distinguish between tax-inclusive and tax-exclusive platform fees depending on verified tax-code status.",
  },
  feeRules: [
    {
      id: "platform_commission_fee",
      type: "percentage",
      label: "Platform Commission Fee",
      description: "Public VN commission formula uses (Item Price - Seller Discount) × category/profile rate.",
      base: "item_after_seller_discount",
      defaultRate: 12.5,
      rateByCategory: {
        default: 12.5,
        mall: 14.5,
      },
      rateByProfile: {
        marketplace: 12.5,
        mall: 14.5,
        verified_tax: 12.5,
      },
    },
    {
      id: "transaction_fee",
      type: "percentage",
      label: "Transaction Fee",
      description: "Public Vietnam transaction fee shown at 5%.",
      base: "seller_revenue_total",
      defaultRate: 5,
    },
    {
      id: "order_processing_fee",
      type: "flat",
      label: "Order Processing Fee",
      description: "Public Vietnam order processing fee per delivered order.",
      defaultAmount: 3000,
    },
    {
      id: "shipping_fee_program",
      type: "flat",
      label: "Shipping Fee Program / Variance",
      description: "Use this manual field when actual package measurements trigger extra shipping cost.",
      sellerInput: true,
      inputLabel: "Shipping fee program charge",
      defaultAmount: 0,
    },
  ],
  manualRateDisclaimer: "Vietnam category-level commission can differ by Marketplace vs Mall and by detailed L3 category. Use the default profile estimate unless you have exact category rates.",
  fulfillmentMethods: [
    {
      value: "self",
      label: "Self / Seller Shipping",
      description: "Model shipping as your own cost or manual shipping program charge.",
      kind: "self",
    },
  ],
  defaults: {
    category: "default",
    sellerProfile: "marketplace",
    fulfillmentMethod: "self",
    soldPrice: 299000,
    sellerDiscount: 10000,
    platformDiscount: 0,
    buyerShippingFee: 20000,
    itemCost: 110000,
    shippingCost: 18000,
    affiliateRate: 10,
    adSpendPerUnit: 15000,
    otherCosts: 0,
    taxRate: 10,
    priceIncludesTax: true,
    manualInputs: { shipping_fee_program: 0 },
  },
  seo: {
    title: "Vietnam TikTok Shop Fee Calculator | SellerLab",
    description: "Calculate Vietnam TikTok Shop commission, transaction fee, order processing fee, tax effect, and profit.",
    h1: "Vietnam TikTok Shop Fee Calculator",
    subtitle: "Based on public Vietnam TikTok Shop fee pages for commission, transaction fee, order processing fee, and platform-fee tax treatment.",
  },
  summary: {
    shortFeeSummary: "Vietnam publicly documents platform commission, 5% transaction fee, and a ₫3,000 order processing fee.",
    taxSummary: "Platform-fee tax treatment changes depending on verified tax-code status; calculator defaults to tax-inclusive public view.",
    fulfillmentSummary: "No public warehouse storage table was found, so fulfillment is modeled via seller shipping plus manual shipping-program charge.",
    disclaimer: "For exact Vietnam category rates, use detailed TikTok category sheets when you have them.",
  },
  docs: [
    {
      title: "Introduction to Seller Fees",
      url: "https://seller-vn.tiktok.com/university/essay?knowledge_id=8858869405370113&lang=en",
      effectiveDate: "2025-10-27 / 2026-03-02 / 2026-04-01",
      scope: "Vietnam seller fee stack overview",
    },
    {
      title: "Platform Commission Fee",
      url: "https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en",
      effectiveDate: "2026-03-02",
      scope: "Vietnam commission formula and default rates",
    },
    {
      title: "Phí Giao Dịch",
      url: "https://seller-vn.tiktok.com/university/essay?knowledge_id=753295858337537",
      effectiveDate: "2026-04-01",
      scope: "Vietnam transaction fee formula",
    },
    {
      title: "Basic Tax Information",
      url: "https://seller-vn.tiktok.com/university/essay?knowledge_id=6837804173133569&lang=en",
      effectiveDate: "2025-07-01",
      scope: "Vietnam VAT/CIT treatment on platform fees",
    },
  ],
  notes: [
    "Vietnam public docs are the strongest among the requested SEA markets for fee and tax accuracy.",
    "Shipping rate cards exist publicly, but the full matrix is attached as files; this calculator leaves route-level shipping as seller input.",
  ],
};
