import {
  type WalmartMarketConfig,
  flat,
  tiered,
} from "../walmart-config";
import { withSuiteBrand } from "@/lib/brand";

const CATEGORIES = [
  { label: "Apparel & Accessories", value: "apparel_accessories" },
  { label: "Automotive & Powersports", value: "automotive_powersports" },
  { label: "Baby", value: "baby" },
  { label: "Beauty", value: "beauty" },
  { label: "Books", value: "books" },
  { label: "Camera & Photo", value: "camera_photo" },
  { label: "Cell Phones", value: "cell_phones" },
  { label: "Consumer Electronics", value: "consumer_electronics" },
  { label: "Electronics Accessories", value: "electronics_accessories" },
  { label: "Entertainment Collectibles", value: "entertainment_collectibles" },
  { label: "Grocery", value: "grocery" },
  { label: "Hardlines", value: "hardlines" },
  { label: "Home", value: "home" },
  { label: "Jewelry", value: "jewelry" },
  { label: "Major Appliances", value: "major_appliances" },
  { label: "Personal Computers", value: "personal_computers" },
  { label: "Tires", value: "tires" },
  { label: "Toys", value: "toys" },
  { label: "Video Game Consoles", value: "video_game_consoles" },
  { label: "Watches", value: "watches" },
  { label: "Everything Else", value: "default" },
] as const;

const REFERRAL_RULES = {
  default: flat(15),
  apparel_accessories: flat(15),
  automotive_powersports: flat(12),
  baby: flat(8),
  beauty: flat(8),
  books: flat(15),
  camera_photo: flat(8),
  cell_phones: flat(8),
  consumer_electronics: flat(8),
  electronics_accessories: flat(15),
  entertainment_collectibles: flat(20),
  grocery: flat(8),
  hardlines: flat(15),
  home: flat(15),
  jewelry: tiered([[250, 20], [Infinity, 5]]),
  major_appliances: flat(8),
  personal_computers: flat(8),
  tires: flat(10),
  toys: flat(15),
  video_game_consoles: flat(8),
  watches: tiered([[1500, 15], [Infinity, 3]]),
};

export const CA_MARKET: WalmartMarketConfig = {
  id: "ca",
  name: "CA",
  fullName: "Canada",
  flag: "🇨🇦",
  domain: "marketplace.walmart.ca",
  currency: { code: "CAD", symbol: "C$", locale: "en-CA", decimals: 2 },
  units: {
    weightLabel: "lb",
    dimensionLabel: "in",
    cubicDivisor: 1728,
    cubicUnitLabel: "cu ft",
  },
  wfs: {
    mode: "ca_official",
    label: "WFS Canada (official public card)",
    helpText: "Uses Walmart Canada WFS public fulfillment and storage card. Fuel surcharge and promo discounts are excluded by default.",
  },
  categories: [...CATEGORIES],
  referralRules: REFERRAL_RULES,
  defaults: {
    category: "home",
    fulfillmentMethod: "wfs",
    soldPrice: 39.99,
    shippingCharged: 0,
    itemCost: 14,
    shippingCost: 8,
    otherCosts: 0,
    paymentProcessingRate: 0,
    usePremiumReferralRate: false,
    unitWeight: 3.2,
    dimensionLength: 12,
    dimensionWidth: 9,
    dimensionHeight: 5,
    isApparel: false,
    isHazmat: false,
    storageMonths: 1,
    storageSeason: "jan_sep",
    manualWfsFulfillmentFee: 0,
    manualWfsShippingRecoveryFee: 0,
    manualWfsStorageFee: 0,
  },
  seo: {
    title: withSuiteBrand("Canada Walmart Fee Calculator"),
    description: "Calculate Walmart Canada referral fees by category and WFS Canada fulfillment/storage costs with source-backed formulas.",
    h1: "Canada Walmart Fee Calculator",
    subtitle: "Source-verified referral fee model plus official WFS Canada fee card logic.",
  },
  summary: {
    shortFeeSummary: "Walmart Canada referral fees are category-based, including tiered Jewelry and Watches rates.",
    referralSummary: "Referral fee applies to total sales price and follows category-specific Canada rules.",
    wfsSummary: "WFS Canada model uses published weight tiers, oversize surcharges, and monthly storage rates.",
    paymentSummary: "Payment processing defaults to 0% unless external processor cost is intentionally added.",
    disclaimer: "Canada WFS table contains threshold jumps; this calculator applies published anchor tiers and incremental rules as documented.",
  },
  docs: [
    {
      title: "Walmart Marketplace Canada Referral Fees",
      url: "https://marketplacelearn.walmart.com/ca/guides/Getting%20started/Complete%20your%20Seller%20Profile/Referral-fees?locale=en-CA",
      asOf: "2026-03-25",
      scope: "Canada referral fee schedule",
    },
    {
      title: "Walmart Fulfillment Services Canada Fees",
      url: "https://marketplacelearn.walmart.com/ca/guides/Walmart%20Fulfillment%20Services%20%28WFS%29/WFS%20basics/wfs-fees?locale=en-CA",
      asOf: "2026-03-25",
      scope: "Canada WFS fulfillment, storage, and oversize surcharges",
    },
  ],
  notes: [
    "Canada WFS uses dimensional weight divisor 300 and adds 0.25 lb packaging before rounding.",
    "Oversize surcharge rules (+C$4 / +C$35) are applied only for units up to 150 lb, per public card.",
    "Fuel surcharge (up to 7%) and temporary promotional discounts are excluded by default and should be modeled manually if applicable.",
  ],
};
