import {
  type WalmartMarketConfig,
  flat,
} from "../walmart-config";
import { withSuiteBrand } from "@/lib/brand";

function keyFromLabel(label: string): string {
  return label
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

const CL_ROWS: Array<[string, number]> = [
  ["Accesorios celulares, TV y computacion, audifonos (accesorios electronicos)", 9.5],
  ["Accesorios fotografia", 14],
  ["Accesorios para instrumentos musicales", 14],
  ["Accesorios para mascotas", 14],
  ["Alimentacion bebe", 11],
  ["Alimentacion y bebestibles", 13],
  ["Almacenamiento y bodega", 18],
  ["Arte y manualidades", 14],
  ["Articulos fiestas y celebraciones", 16],
  ["Articulos para la construccion", 14],
  ["Automovil otros", 12],
  ["Bebidas alcoholicas", 10],
  ["Belleza y salud", 13],
  ["Bolsos y mochilas", 13],
  ["Cables", 13],
  ["Calzado", 16],
  ["Camaras y lentes", 12],
  ["Ciclismo", 12],
  ["Combustibles y lubricantes", 12],
  ["Comida para mascotas", 8],
  ["Computadores y tablets", 9.5],
  ["Cuidado personal", 13],
  ["Cuidado, panales para bebes y otros", 11],
  ["Decoracion de hogar, cocina y otros", 15],
  ["Deportes y camping", 14],
  ["Discos duros, memorias y componentes computacion", 13],
  ["Disfraces", 16],
  ["Electricidad", 16],
  ["Equipos de audio, sonido y grabacion", 9.5],
  ["Estuches y bolsos de musica", 14],
  ["Farmacia y suplementos", 15],
  ["Ferreteria", 14],
  ["Herramientas", 13],
  ["Impresoras, scanners y otros", 9.5],
  ["Instrumentos musicales", 14],
  ["Jardin y terraza", 14],
  ["Joyeria", 18],
  ["Juguetes", 16],
  ["Juguetes y recreacion bebe", 14],
  ["Libros y revistas", 14],
  ["Limpieza y productos quimicos domesticos e industriales", 15],
  ["Linea blanca y electrodomesticos", 9.5],
  ["Llantas y componentes neumaticos", 12],
  ["Maletas y accesorios", 15],
  ["Muebles", 14],
  ["Muebles bebes", 14],
  ["Musica", 14],
  ["Neumaticos", 12],
  ["Oficina", 14],
  ["Optica", 18],
  ["Otros ferreteria", 15],
  ["Otros mascotas", 14],
  ["Parrillas y cocina al aire libre", 15],
  ["Partes y accesorios automovil", 12],
  ["Peliculas", 14],
  ["Plomeria y HVAC", 14],
  ["Primeros auxilios", 15],
  ["Proyectores de video", 9.5],
  ["Regalos y premios", 15],
  ["Relojes", 18],
  ["Ropa de cama", 15],
  ["Salud y aseo para mascotas", 14],
  ["Seguridad y emergencia", 15],
  ["Series de television", 14],
  ["Smartwatches, smarthome, audio, consolas y conexion", 9.5],
  ["Telefonia", 9.5],
  ["Telescopios y otros", 15],
  ["Televisores y monitores", 9.5],
  ["Transporte bebe", 14],
  ["Vestuario", 16],
  ["Vestuario bebe", 15],
  ["Videojuegos", 9.5],
];

const CATEGORIES = CL_ROWS.map(([label]) => ({ label, value: keyFromLabel(label) }));
const REFERRAL_RULES = {
  default: flat(15),
  ...Object.fromEntries(CL_ROWS.map(([label, rate]) => [keyFromLabel(label), flat(rate)])),
};

export const CL_MARKET: WalmartMarketConfig = {
  id: "cl",
  name: "CL",
  fullName: "Chile",
  flag: "🇨🇱",
  domain: "marketplace.walmartchile.cl",
  currency: { code: "CLP", symbol: "$", locale: "es-CL", decimals: 0 },
  units: {
    weightLabel: "kg",
    dimensionLabel: "cm",
    cubicDivisor: 1_000_000,
    cubicUnitLabel: "m3",
  },
  wfs: {
    mode: "cl_official",
    label: "WFS Chile (official public card)",
    helpText: "Uses Chile WFS size-tier table by chargeable weight and daily storage rates by m3.",
  },
  categories: [...CATEGORIES, { label: "Todo lo demas", value: "default" }],
  referralRules: REFERRAL_RULES,
  defaults: {
    category: keyFromLabel("Decoracion de hogar, cocina y otros"),
    fulfillmentMethod: "wfs",
    soldPrice: 29990,
    shippingCharged: 0,
    itemCost: 12000,
    shippingCost: 3900,
    otherCosts: 0,
    paymentProcessingRate: 0,
    usePremiumReferralRate: false,
    unitWeight: 3,
    dimensionLength: 30,
    dimensionWidth: 25,
    dimensionHeight: 15,
    isApparel: false,
    isHazmat: false,
    storageMonths: 4,
    storageSeason: "jan_sep",
    manualWfsFulfillmentFee: 0,
    manualWfsShippingRecoveryFee: 0,
    manualWfsStorageFee: 0,
  },
  seo: {
    title: withSuiteBrand("Chile Walmart Fee Calculator"),
    description: "Calculate Walmart Chile referral fees by category and WFS Chile fulfillment/storage with source-backed public fee tables.",
    h1: "Chile Walmart Fee Calculator",
    subtitle: "Source-based Chile model with category referral rates and WFS size-tier fulfillment pricing.",
  },
  summary: {
    shortFeeSummary: "Walmart Chile referral fees vary by category, with electronics often near 9.5% and higher-fee categories up to 18%.",
    referralSummary: "Referral fee follows the published Chile category commission table.",
    wfsSummary: "WFS Chile applies fulfillment fee by size tier (chargeable kg) plus daily storage fee per m3 after month thresholds.",
    paymentSummary: "Payment processing defaults to 0% unless you model external provider costs.",
    disclaimer: "For Chile WFS, enter chargeable weight as defined by your operation; volumetric conversion rules can vary by logistics program settings.",
  },
  docs: [
    {
      title: "Walmart Marketplace Chile - Tabla de comisiones",
      url: "https://marketplacelearn.walmart.com/cl/guides/Transf%C3%B3rmate%20en%20nuestro%20Seller/Sobre%20nuestro%20Marketplace/tabla-de-comisiones",
      asOf: "2026-03-25",
      scope: "Chile category commission table",
    },
    {
      title: "Walmart Marketplace Chile - Tarifas WFS",
      url: "https://marketplacelearn.walmart.com/cl/guides/Walmart%20Fulfillment%20Services/Walmart%20Fulfillment%20Services/tarifas-wfs",
      asOf: "2026-03-25",
      scope: "Chile WFS fulfillment and storage tariffs",
    },
  ],
  notes: [
    "Chile WFS fulfillment is modeled by published size tiers (XS to XL) using chargeable weight brackets.",
    "Chile storage applies daily m3 charges after month thresholds (0-3 free, then paid tiers).",
  ],
};
