import {
  type WalmartMarketConfig,
  flat,
  tiered,
} from "../walmart-config";
import { withSuiteBrand } from "@/lib/brand";

const CATEGORIES = [
  { label: "Apparel & Accessories", value: "apparel_accessories" },
  { label: "Automotive & Powersports", value: "automotive_powersports" },
  { label: "Baby", value: "baby" },
  { label: "Beauty", value: "beauty" },
  { label: "Books", value: "books" },
  { label: "Camera & Photo", value: "camera_photo" },
  { label: "Cell Phones", value: "cell_phones" },
  { label: "Consumer Electronics", value: "consumer_electronics" },
  { label: "Electronics Accessories", value: "electronics_accessories" },
  { label: "Grocery", value: "grocery" },
  { label: "Health & Personal Care", value: "health_personal_care" },
  { label: "Home & Garden", value: "home_garden" },
  { label: "Jewelry", value: "jewelry" },
  { label: "Kitchen", value: "kitchen" },
  { label: "Major Appliances", value: "major_appliances" },
  { label: "Music", value: "music" },
  { label: "Musical Instruments", value: "musical_instruments" },
  { label: "Office Products", value: "office_products" },
  { label: "Office Products - Printer Ink & Toner", value: "office_printer_cartridges" },
  { label: "Outdoors", value: "outdoors" },
  { label: "Outdoors - Hunting / Scopes / Binoculars", value: "outdoors_optics" },
  { label: "Personal Computers", value: "personal_computers" },
  { label: "Pet Supplies", value: "pet_supplies" },
  { label: "Plumbing, Heating, Cooling & Ventilation", value: "phcv" },
  { label: "Software & Computer Video Games", value: "software_games" },
  { label: "Sports", value: "sports" },
  { label: "Sports Collectibles", value: "sports_collectibles" },
  { label: "Tires & Wheels", value: "tires_wheels" },
  { label: "Tools & Home Improvement", value: "tools_home_improvement" },
  { label: "Toys & Games", value: "toys_games" },
  { label: "Video & DVD", value: "video_dvd" },
  { label: "Video Game Consoles", value: "video_game_consoles" },
  { label: "Watches", value: "watches" },
  { label: "Everything Else", value: "default" },
] as const;

const REFERRAL_RULES = {
  default: flat(15),
  apparel_accessories: flat(15),
  automotive_powersports: flat(12),
  baby: flat(8),
  beauty: flat(8),
  books: flat(15),
  camera_photo: flat(8),
  cell_phones: flat(8),
  consumer_electronics: flat(8),
  electronics_accessories: flat(15),
  grocery: flat(8),
  health_personal_care: flat(8),
  home_garden: flat(15),
  jewelry: tiered([[250, 20], [Infinity, 5]]),
  kitchen: flat(15),
  major_appliances: flat(8),
  music: flat(15),
  musical_instruments: flat(12),
  office_products: flat(15),
  office_printer_cartridges: flat(12),
  outdoors: flat(15),
  outdoors_optics: flat(8),
  personal_computers: flat(6),
  pet_supplies: flat(15),
  phcv: flat(10),
  software_games: flat(15),
  sports: flat(15),
  sports_collectibles: flat(20),
  tires_wheels: flat(10),
  tools_home_improvement: flat(15),
  toys_games: flat(15),
  video_dvd: flat(15),
  video_game_consoles: flat(8),
  watches: tiered([[1500, 15], [Infinity, 3]]),
};

export const US_MARKET: WalmartMarketConfig = {
  id: "us",
  name: "US",
  fullName: "United States",
  flag: "🇺🇸",
  domain: "marketplace.walmart.com",
  currency: { code: "USD", symbol: "$", locale: "en-US", decimals: 2 },
  units: {
    weightLabel: "lb",
    dimensionLabel: "in",
    cubicDivisor: 1728,
    cubicUnitLabel: "cu ft",
  },
  wfs: {
    mode: "us_official",
    label: "WFS (US official public card)",
    helpText: "Uses Walmart US public WFS fulfillment formulas, surcharge rules, and monthly storage references.",
  },
  categories: [...CATEGORIES],
  referralRules: REFERRAL_RULES,
  defaults: {
    category: "home_garden",
    fulfillmentMethod: "wfs",
    soldPrice: 25,
    shippingCharged: 0,
    itemCost: 8,
    shippingCost: 4.5,
    otherCosts: 0,
    paymentProcessingRate: 0,
    usePremiumReferralRate: false,
    unitWeight: 1.2,
    dimensionLength: 10,
    dimensionWidth: 8,
    dimensionHeight: 4,
    isApparel: false,
    isHazmat: false,
    storageMonths: 0,
    storageSeason: "jan_sep",
    manualWfsFulfillmentFee: 0,
    manualWfsShippingRecoveryFee: 0,
    manualWfsStorageFee: 0,
  },
  seo: {
    title: withSuiteBrand("US Walmart Fee Calculator"),
    description: "Calculate Walmart US referral fees by category, WFS fulfillment fees, optional payment processing fees, and net profit with source-verified formulas.",
    h1: "US Walmart Fee Calculator",
    subtitle: "Data-verified US model for referral fees, WFS costs, and profit breakdown.",
  },
  summary: {
    shortFeeSummary: "Walmart US referral fees are category-based and span 6% to 20%, with tiered rules for Jewelry and Watches.",
    referralSummary: "Referral fee = category rate applied to total sales price (item + shipping charged).",
    wfsSummary: "WFS uses public US formulas for standard and big-bulky fulfillment plus storage by season.",
    paymentSummary: "Public pricing states no setup/monthly/hidden fees. Payment processing stays at 0% unless you model external costs.",
    disclaimer: "Rates are based on Walmart public documentation and should be rechecked before pricing decisions.",
  },
  docs: [
    {
      title: "Walmart Marketplace Pricing (US referral + WFS)",
      url: "https://marketplace.walmart.com/pricing/",
      asOf: "2026-03-25",
      scope: "US referral fees, WFS fulfillment and storage",
    },
    {
      title: "Walmart Fulfillment Services Pricing (US)",
      url: "https://marketplace.walmart.com/walmart-fulfillment-services-pricing/",
      asOf: "2026-03-25",
      scope: "US WFS formula detail",
    },
  ],
  notes: [
    "Referral fee base uses total sales price (item + shipping charged), aligned with Walmart US public formula.",
    "US WFS uses dimensional divisor 139 and 0.25 lb packaging before rounding shipping weight.",
    "US WFS surcharges in this model include low-price (+$1), apparel (+$0.50), and hazmat (+$0.75) for standard items.",
  ],
};
