import type { ShopifyMarketConfig } from "../shopify-config";

export const CA_MARKET: ShopifyMarketConfig = {
  id: "ca",
  name: "CA",
  fullName: "Canada",
  flag: "🇨🇦",
  domain: "shopify.com/ca",
  currency: { code: "CAD", symbol: "C$", locale: "en-CA", decimals: 2 },
  tax: {
    name: "GST",
    defaultRate: 5,
    priceIncludesTaxByDefault: false,
    taxOnSubscription: true,
    taxOnShopifyPaymentsFee: false,
    taxOnShopifyTransactionFee: true,
    helpText: "Canada is modeled as tax-exclusive pricing by default. Shopify Payments processing fees are not taxed in this model.",
  },
  plans: [
    {
      value: "basic",
      label: "Basic",
      subscriptionByCycle: { monthly: 51, yearly: 38 },
      shopifyPaymentsRate: 2.9,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 2,
    },
    {
      value: "shopify",
      label: "Shopify (Grow)",
      subscriptionByCycle: { monthly: 132, yearly: 99 },
      shopifyPaymentsRate: 2.7,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 1,
    },
    {
      value: "advanced",
      label: "Advanced",
      subscriptionByCycle: { monthly: 517, yearly: 389 },
      shopifyPaymentsRate: 2.5,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 0.5,
    },
  ],
  defaults: {
    plan: "basic",
    billingCycle: "monthly",
    usesShopifyPayments: true,
    soldPrice: 69.99,
    shippingCharged: 9.99,
    ordersPerMonth: 120,
    itemCost: 24,
    shippingCost: 8,
    marketingCost: 6,
    otherCostsPerOrder: 1.5,
    monthlyAppCost: 49,
    monthlyOperationalCost: 160,
    taxRate: 5,
    priceIncludesTax: false,
    salesTaxPerOrder: 0,
    thirdPartyProcessorRate: 2.9,
    thirdPartyProcessorFixedFee: 0.30,
  },
  seo: {
    title: "Shopify Fees Canada Calculator (CAD) | SellerLab",
    description: "Estimate Shopify fees Canada sellers pay, including Shopify Payments rates, third-party transaction fees, GST handling, and per-order profit in CAD.",
    h1: "Shopify Fees Canada Calculator",
    subtitle: "Model Shopify Canada plan costs, payment fees, GST settings, and net margin per order.",
  },
  summary: {
    shortFeeSummary: "Includes Shopify plan allocation, Shopify Payments card fees, and optional third-party processor + Shopify transaction fees.",
    paymentSummary: "Canada Shopify Payments rates vary by plan. When Shopify Payments is disabled, Shopify transaction fees still apply by plan.",
    subscriptionSummary: "Monthly fixed costs are allocated per order from plan subscription, app spend, and operational overhead.",
    taxSummary: "GST defaults to 5% and tax-exclusive pricing. Shopify Payments processing fees are modeled as non-taxable in Canada.",
    disclaimer: "Actual rates can vary by card mix, provider agreement, and account terms. Confirm values in Shopify Admin before final planning.",
  },
  docs: [
    {
      title: "Shopify Pricing (Canada)",
      url: "https://www.shopify.com/ca/pricing",
      scope: "Plan pricing and Shopify Payments rates",
    },
    {
      title: "Third-party transaction fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/billing-charges/types-of-charges/third-party-charges/third-party-transaction-fees",
      scope: "Plan-based Shopify transaction fee behavior",
    },
    {
      title: "Taxes on Shopify fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/your-invoice/charges#taxes-on-your-shopify-fees",
      scope: "Regional tax behavior for Shopify charges",
    },
  ],
  notes: [
    "GST/HST/PST treatment can vary by province; this calculator uses a baseline 5% GST model.",
    "Shopify Payments fee tax is set to zero in this Canada model per the requirement.",
    "Use your real third-party processor rates when Shopify Payments is disabled.",
  ],
};
