import type { ShopifyMarketConfig } from "../shopify-config";

export const CH_MARKET: ShopifyMarketConfig = {
  id: "ch",
  name: "CH",
  fullName: "Switzerland",
  flag: "🇨🇭",
  domain: "shopify.com/ch",
  currency: { code: "CHF", symbol: "CHF ", locale: "de-CH", decimals: 2 },
  tax: {
    name: "VAT",
    defaultRate: 7.7,
    priceIncludesTaxByDefault: true,
    taxOnSubscription: true,
    taxOnShopifyPaymentsFee: true,
    taxOnShopifyTransactionFee: true,
    helpText: "Switzerland is modeled as VAT-inclusive pricing by default. VAT is applied to Shopify fees in this model.",
  },
  plans: [
    {
      value: "basic",
      label: "Basic",
      subscriptionByCycle: { monthly: 28, yearly: 21 },
      shopifyPaymentsRate: 2.95,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 2,
    },
    {
      value: "shopify",
      label: "Shopify (Grow)",
      subscriptionByCycle: { monthly: 79, yearly: 59 },
      shopifyPaymentsRate: 2.75,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 1,
    },
    {
      value: "advanced",
      label: "Advanced",
      subscriptionByCycle: { monthly: 359, yearly: 269 },
      shopifyPaymentsRate: 2.55,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 0.6,
    },
  ],
  defaults: {
    plan: "basic",
    billingCycle: "monthly",
    usesShopifyPayments: true,
    soldPrice: 69.90,
    shippingCharged: 8.90,
    ordersPerMonth: 120,
    itemCost: 24,
    shippingCost: 8,
    marketingCost: 6,
    otherCostsPerOrder: 1.5,
    monthlyAppCost: 45,
    monthlyOperationalCost: 155,
    taxRate: 7.7,
    priceIncludesTax: true,
    salesTaxPerOrder: 0,
    thirdPartyProcessorRate: 2.9,
    thirdPartyProcessorFixedFee: 0.30,
  },
  seo: {
    title: "Shopify Fees Switzerland Calculator (CHF) | SellerLab",
    description: "Calculate Shopify Switzerland fees in CHF with VAT-inclusive pricing, Shopify Payments rates, third-party transaction fees, and per-order profit.",
    h1: "Shopify Fees Switzerland Calculator",
    subtitle: "Estimate Shopify Switzerland costs with 7.7% VAT defaults, plan fees, and payment processing charges.",
  },
  summary: {
    shortFeeSummary: "Includes subscription allocation, Shopify Payments card fees, and optional third-party processor + Shopify transaction fees.",
    paymentSummary: "Switzerland Shopify Payments rates are modeled at 2.55%-2.95% + CHF 0.30 by plan, with configurable third-party processor costs.",
    subscriptionSummary: "Plan subscription, app spend, and operating overhead are allocated per order to expose true margin.",
    taxSummary: "VAT defaults to 7.7% and is modeled as included in customer price. VAT is applied to Shopify fee components.",
    disclaimer: "Final billing can vary by card type, dispute profile, and contract terms. Confirm rates and taxes in your Shopify Admin.",
  },
  docs: [
    {
      title: "Shopify Pricing (Switzerland)",
      url: "https://www.shopify.com/ch/preise",
      scope: "Plan pricing and online card rates in CHF",
    },
    {
      title: "Third-party transaction fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/billing-charges/types-of-charges/third-party-charges/third-party-transaction-fees",
      scope: "Shopify transaction fee when using external processors",
    },
    {
      title: "Taxes on Shopify fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/your-invoice/charges#taxes-on-your-shopify-fees",
      scope: "Tax behavior for Shopify subscription and processing fees",
    },
  ],
  notes: [
    "CH market defaults to VAT-inclusive pricing and applies VAT to Shopify fee components.",
    "Switzerland uses a lower default VAT rate (7.7%) than EU/UK models.",
    "Switch off Shopify Payments to compare external gateway + Shopify transaction fee economics.",
  ],
};
