import type { ShopifyMarketConfig } from "../shopify-config";

export const EU_MARKET: ShopifyMarketConfig = {
  id: "eu",
  name: "EU",
  fullName: "European Union",
  flag: "🇪🇺",
  domain: "shopify.com/ie",
  currency: { code: "EUR", symbol: "€", locale: "en-IE", decimals: 2 },
  tax: {
    name: "VAT",
    defaultRate: 20,
    priceIncludesTaxByDefault: true,
    taxOnSubscription: true,
    taxOnShopifyPaymentsFee: true,
    taxOnShopifyTransactionFee: true,
    helpText: "EU pricing is modeled as VAT-inclusive by default. VAT rates vary by country and reverse-charge status, so adjust as needed.",
  },
  plans: [
    {
      value: "basic",
      label: "Basic",
      subscriptionByCycle: { monthly: 32, yearly: 24 },
      shopifyPaymentsRate: 2.0,
      shopifyPaymentsFixedFee: 0.25,
      thirdPartyTransactionRate: 2,
    },
    {
      value: "shopify",
      label: "Shopify (Grow)",
      subscriptionByCycle: { monthly: 92, yearly: 69 },
      shopifyPaymentsRate: 1.7,
      shopifyPaymentsFixedFee: 0.25,
      thirdPartyTransactionRate: 1,
    },
    {
      value: "advanced",
      label: "Advanced",
      subscriptionByCycle: { monthly: 385, yearly: 289 },
      shopifyPaymentsRate: 1.5,
      shopifyPaymentsFixedFee: 0.25,
      thirdPartyTransactionRate: 0.6,
    },
  ],
  defaults: {
    plan: "basic",
    billingCycle: "monthly",
    usesShopifyPayments: true,
    soldPrice: 59.99,
    shippingCharged: 6.99,
    ordersPerMonth: 120,
    itemCost: 20,
    shippingCost: 7,
    marketingCost: 5,
    otherCostsPerOrder: 1.5,
    monthlyAppCost: 39,
    monthlyOperationalCost: 140,
    taxRate: 20,
    priceIncludesTax: true,
    salesTaxPerOrder: 0,
    thirdPartyProcessorRate: 2.9,
    thirdPartyProcessorFixedFee: 0.25,
  },
  seo: {
    title: "Shopify Fees EU Calculator (EUR) | SellerLab",
    description: "Calculate Shopify EU costs and profit using VAT-inclusive pricing, Shopify Payments rates, third-party transaction fees, and overhead allocation in EUR.",
    h1: "Shopify Fees EU Calculator",
    subtitle: "Model European Union Shopify costs with VAT-inclusive pricing and plan-level payment fee assumptions.",
  },
  summary: {
    shortFeeSummary: "Includes plan subscription allocation, Shopify Payments rates, and optional third-party processor + Shopify transaction fees.",
    paymentSummary: "EU Shopify Payments rates vary by country and plan. This model uses a practical EU baseline and keeps third-party gateway inputs configurable.",
    subscriptionSummary: "Monthly plan, app, and operating costs are allocated across order volume to produce realistic per-order economics.",
    taxSummary: "VAT defaults to 20% and price-inclusive mode. VAT is modeled on Shopify subscription, payment, and transaction fees.",
    disclaimer: "Published rates and VAT treatment differ by country/entity setup. Confirm live values in your Shopify Admin before financial decisions.",
  },
  docs: [
    {
      title: "Shopify Pricing (Ireland, EUR reference)",
      url: "https://www.shopify.com/ie/pricing",
      scope: "EU-denominated plan pricing and online card rate reference",
    },
    {
      title: "Third-party transaction fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/billing-charges/types-of-charges/third-party-charges/third-party-transaction-fees",
      scope: "Plan-based Shopify transaction fee behavior",
    },
    {
      title: "Taxes on Shopify fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/your-invoice/charges#taxes-on-your-shopify-fees",
      scope: "VAT handling for Shopify charges and processing fees",
    },
  ],
  notes: [
    "EU fees differ by country and payment method mix. This calculator uses a single EU baseline for planning.",
    "VAT is modeled as included in sale price and applied to Shopify fee components.",
    "If your account has VAT reverse-charge treatment, lower the VAT rate to match your invoice reality.",
  ],
};
