import type { ShopifyMarketConfig } from "../shopify-config";

export const SG_MARKET: ShopifyMarketConfig = {
  id: "sg",
  name: "SG",
  fullName: "Singapore",
  flag: "🇸🇬",
  domain: "shopify.com/sg",
  currency: { code: "SGD", symbol: "S$", locale: "en-SG", decimals: 2 },
  tax: {
    name: "GST",
    defaultRate: 9,
    priceIncludesTaxByDefault: true,
    taxOnSubscription: true,
    taxOnShopifyPaymentsFee: true,
    taxOnShopifyTransactionFee: true,
    helpText: "Singapore is modeled as GST-inclusive pricing by default. GST is applied to Shopify fees in this model.",
  },
  plans: [
    {
      value: "basic",
      label: "Basic",
      subscriptionByCycle: { monthly: 40, yearly: 30 },
      shopifyPaymentsRate: 3.4,
      shopifyPaymentsFixedFee: 0.50,
      thirdPartyTransactionRate: 2,
    },
    {
      value: "shopify",
      label: "Shopify (Grow)",
      subscriptionByCycle: { monthly: 108, yearly: 81 },
      shopifyPaymentsRate: 3.3,
      shopifyPaymentsFixedFee: 0.50,
      thirdPartyTransactionRate: 1,
    },
    {
      value: "advanced",
      label: "Advanced",
      subscriptionByCycle: { monthly: 410, yearly: 307 },
      shopifyPaymentsRate: 3.2,
      shopifyPaymentsFixedFee: 0.50,
      thirdPartyTransactionRate: 0.6,
    },
  ],
  defaults: {
    plan: "basic",
    billingCycle: "monthly",
    usesShopifyPayments: true,
    soldPrice: 69.90,
    shippingCharged: 5.90,
    ordersPerMonth: 120,
    itemCost: 24,
    shippingCost: 6,
    marketingCost: 5,
    otherCostsPerOrder: 1.5,
    monthlyAppCost: 49,
    monthlyOperationalCost: 150,
    taxRate: 9,
    priceIncludesTax: true,
    salesTaxPerOrder: 0,
    thirdPartyProcessorRate: 3.4,
    thirdPartyProcessorFixedFee: 0.50,
  },
  seo: {
    title: "Shopify Fees Singapore Calculator (SGD) | SellerLab",
    description: "Estimate Shopify fees Singapore merchants pay, including 3.2%-3.4% processing rates, third-party transaction fees, GST handling, and per-order profit in SGD.",
    h1: "Shopify Fees Singapore Calculator",
    subtitle: "Model Shopify Singapore costs with GST-inclusive pricing, payment fees, and profit per order.",
  },
  summary: {
    shortFeeSummary: "Includes Shopify plan allocation, Shopify Payments card fees, and optional third-party gateway plus Shopify transaction fees.",
    paymentSummary: "Singapore Shopify Payments rates are modeled at 3.2%-3.4% + S$0.50 by plan. Third-party gateways still incur Shopify transaction fees.",
    subscriptionSummary: "Subscription and monthly overhead are allocated by order volume for realistic per-order profitability.",
    taxSummary: "GST defaults to 9% and is price-inclusive. Shopify fees are modeled with GST applied.",
    disclaimer: "Use this as an operational estimate. Confirm current Singapore pricing and payment terms in your Shopify Admin.",
  },
  docs: [
    {
      title: "Shopify Pricing (Singapore)",
      url: "https://www.shopify.com/sg/pricing",
      scope: "Plan pricing and Shopify Payments overview",
    },
    {
      title: "Third-party transaction fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/billing-charges/types-of-charges/third-party-charges/third-party-transaction-fees",
      scope: "Additional Shopify fee when not using Shopify Payments",
    },
    {
      title: "Taxes on Shopify fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/your-invoice/charges#taxes-on-your-shopify-fees",
      scope: "GST treatment on Shopify invoiced services",
    },
  ],
  notes: [
    "Price includes GST by default, and the calculator derives tax-exclusive revenue for margin calculations.",
    "Shopify fee GST is applied to subscription and Shopify payment/transaction fees in this market model.",
    "Switch off Shopify Payments to compare third-party processor economics plus Shopify transaction fees.",
  ],
};
