import type { ShopifyMarketConfig } from "../shopify-config";

export const US_MARKET: ShopifyMarketConfig = {
  id: "us",
  name: "US",
  fullName: "United States",
  flag: "🇺🇸",
  domain: "shopify.com",
  currency: { code: "USD", symbol: "$", locale: "en-US", decimals: 2 },
  tax: {
    name: "Sales tax",
    defaultRate: 0,
    priceIncludesTaxByDefault: false,
    taxOnSubscription: false,
    taxOnShopifyPaymentsFee: false,
    taxOnShopifyTransactionFee: false,
    helpText: "US pricing is usually pre-tax and tax treatment differs by state. Keep tax manual unless you have a specific remittance model.",
  },
  plans: [
    {
      value: "basic",
      label: "Basic",
      subscriptionByCycle: { monthly: 39, yearly: 29 },
      shopifyPaymentsRate: 2.9,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 2,
    },
    {
      value: "shopify",
      label: "Shopify (Grow)",
      subscriptionByCycle: { monthly: 105, yearly: 79 },
      shopifyPaymentsRate: 2.7,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 1,
    },
    {
      value: "advanced",
      label: "Advanced",
      subscriptionByCycle: { monthly: 399, yearly: 299 },
      shopifyPaymentsRate: 2.5,
      shopifyPaymentsFixedFee: 0.30,
      thirdPartyTransactionRate: 0.6,
    },
  ],
  defaults: {
    plan: "basic",
    billingCycle: "monthly",
    usesShopifyPayments: true,
    soldPrice: 49.99,
    shippingCharged: 4.99,
    ordersPerMonth: 120,
    itemCost: 18,
    shippingCost: 6,
    marketingCost: 5,
    otherCostsPerOrder: 1,
    monthlyAppCost: 39,
    monthlyOperationalCost: 120,
    taxRate: 0,
    priceIncludesTax: false,
    salesTaxPerOrder: 0,
    thirdPartyProcessorRate: 2.9,
    thirdPartyProcessorFixedFee: 0.30,
  },
  seo: {
    title: "US Shopify Cost Calculator | SellerLab",
    description: "Calculate Shopify US costs and profit with subscription plans, Shopify Payments fees, third-party transaction fees, and operating expenses.",
    h1: "US Shopify Cost Calculator",
    subtitle: "Estimate per-order Shopify costs and net profit using Basic, Shopify (Grow), and Advanced plan fee structures.",
  },
  summary: {
    shortFeeSummary: "Includes plan subscription allocation, Shopify Payments card fees, and optional third-party gateway + Shopify transaction fees.",
    paymentSummary: "Shopify Payments rates vary by plan. If you use a third-party provider, Shopify applies an additional plan-based transaction fee.",
    subscriptionSummary: "Plan subscription costs can be modeled as monthly-billed or yearly-billed monthly equivalents and allocated per order volume.",
    taxSummary: "Sales tax is configurable. By default, US prices are treated as tax-exclusive and tax remitted is manual.",
    disclaimer: "Rates vary by plan, payment method, and commercial agreement. Verify your current Admin billing and payment fee tables before final decisions.",
  },
  docs: [
    {
      title: "Shopify Pricing (US)",
      url: "https://www.shopify.com/pricing?country=us",
      scope: "Plan pricing and card rate overview",
    },
    {
      title: "Third-party transaction fees",
      url: "https://help.shopify.com/en/manual/your-account/manage-billing/billing-charges/types-of-charges/third-party-charges/third-party-transaction-fees",
      scope: "Transaction fee behavior when not using Shopify Payments",
    },
    {
      title: "Shopify Payments",
      url: "https://help.shopify.com/en/manual/payments/shopify-payments",
      scope: "Shopify Payments documentation and eligibility",
    },
  ],
  notes: [
    "This calculator models online-card transactions and allocates monthly fixed costs to each order.",
    "Third-party provider processing fees vary by provider and agreement; enter your actual processor rate for best accuracy.",
    "Sales tax is intentionally manual because US tax treatment varies by state and nexus setup.",
  ],
};
